sudo: required
dist: trusty

branches:
  except:
  #- l10n_dev

language: node_js
node_js:
  - "8"
  
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

env:
  - TRAVIS_NODE_VERSION="7.9.0"
cache:
   directories:
     - $(npm root -g)
     - node_modules

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/063276d3941fa8443947
    on_success: always  # options: [always|never|change] default: change
    on_failure: always  # options: [always|never|change] default: always
    on_start: never    # options: [always|never|change] default: never

services:
  - docker

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  #- travis_retry npm install -g codeceptjs
  #- travis_retry npm install -g webdriverio
  #- travis_retry npm install -g cookie

before_install:
# docker pull portainer/portainer
# sudo docker run -d -p 9000:9000 --name treehouse -v /var/run/docker.sock:/var/run/docker.sock portainer:portainer
# Add CouchDB Docker
  - docker pull klaemo/couchdb:2.0.0
  - sudo docker run -d -p 5984:5984 -p 5986:5986 --name planet -v /srv/data/bell:/usr/local/var/lib/couchdb -v /srv/log/bell:/usr/local/var/log/couchdb klaemo/couchdb:2.0.0
# Set up Node.js
  #- curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh
  #- bash nodesource_setup.sh
  #- apt-get -y install nodejs

# Add CORS to CouchDB so app has access to databases
  - git clone https://github.com/pouchdb/add-cors-to-couchdb.git
  - cd add-cors-to-couchdb
  - npm install
  - node bin.js http://localhost:5984
  - cd ..
  # End add CORS to CouchDB

# Add initial Couch databases here
  - curl -X PUT http://127.0.0.1:5984/_users
  - curl -X PUT http://127.0.0.1:5984/_replicator
  - curl -X PUT http://127.0.0.1:5984/_global_changes
  - curl -X PUT http://127.0.0.1:5984/meetups
# End Couch database addition

  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install
- npm install -g @angular/cli
- npm install -g karma
#- ng build

script:
  - export
  - docker ps -a | grep planet
  - curl -X GET http://127.0.0.1:5984/_all_dbs
  - i=$(curl -X GET http://127.0.0.1:5984/_all_dbs | jq length); if [ $i -ne 4 ]; then exit 1; fi
  - node -v
  #- ng test
  #- ng e2e
