services:
  couchdb:
    expose:
      - 5984
    image: klaemo/couchdb
    ports:
      - "5984:5984"
  db-init:
    build:
      context: ./db-init/
    depends_on:
      - couchdb
  planet:
    build:
      context: ./planet/
    ports:
      - "3000:3000"
    volumes:
      - "../:/planet"
    depends_on:
      - couchdb
version: "2"
