services:
  couchdb:
    expose:
      - 5984
    image: treehouses/couchdb:2.1.1
    ports:
      - "2300:5984"
  db-init:
    image: treehouses/planet:db-init-0.2.0
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
  planet:
    image: treehouses/planet:0.2.0
    ports:
      - "3100:80"
    environment:
      - MULTIPLE_IPS=true
      - HOST_PROTOCOL=http
      - DB_HOST=127.0.0.1
      - DB_PORT=2300
      - CENTER_ADDRESS=earth.ole.org:2200
    depends_on:
      - couchdb
version: "2"
